# Generated by Django 5.0.1 on 2026-09-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("date", models.DateField()),
                ("total_tasks", models.PositiveIntegerField(default=0)),
                ("completed_tasks", models.PositiveIntegerField(default=0)),
                ("pending_tasks", models.PositiveIntegerField(default=0)),
                ("overdue_tasks", models.PositiveIntegerField(default=0)),
                (
                    "average_completion_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "category statistics",
                "verbose_name_plural": "category statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyTaskStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("date", models.DateField()),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("tasks_overdue", models.PositiveIntegerField(default=0)),
                ("tasks_pending", models.PositiveIntegerField(default=0)),
                ("tasks_in_progress", models.PositiveIntegerField(default=0)),
                (
                    "total_hours_logged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("comments_added", models.PositiveIntegerField(default=0)),
                ("tasks_assigned_to_others", models.PositiveIntegerField(default=0)),
                ("tasks_received", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "daily task statistics",
                "verbose_name_plural": "daily task statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductivityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("summary", models.JSONField(default=dict)),
                ("total_tasks_completed", models.PositiveIntegerField(default=0)),
                (
                    "total_hours_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "productivity_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tasks_by_category", models.JSONField(default=dict)),
                ("tasks_by_priority", models.JSONField(default=dict)),
                ("completion_trend", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "productivity report",
                "verbose_name_plural": "productivity reports",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("date", models.DateField()),
                ("team_size", models.PositiveIntegerField(default=0)),
                ("total_tasks", models.PositiveIntegerField(default=0)),
                ("completed_tasks", models.PositiveIntegerField(default=0)),
                ("overdue_tasks", models.PositiveIntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_completion_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "team statistics",
                "verbose_name_plural": "team statistics",
                "ordering": ["-date"],
            },
        ),
    ]
