# Generated by Django 5.0.1 on 2026-09-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_completed", "Task Completed"),
                            ("task_overdue", "Task Overdue"),
                            ("task_due_soon", "Task Due Soon"),
                            ("comment_added", "Comment Added"),
                            ("mention", "Mentioned in Comment"),
                            ("task_updated", "Task Updated"),
                            ("team_update", "Team Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("is_push_sent", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("action_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("email_task_assigned", models.BooleanField(default=True)),
                ("email_task_completed", models.BooleanField(default=True)),
                ("email_task_overdue", models.BooleanField(default=True)),
                ("email_task_due_soon", models.BooleanField(default=True)),
                ("email_comment_added", models.BooleanField(default=True)),
                ("email_mention", models.BooleanField(default=True)),
                ("email_digest", models.BooleanField(default=True)),
                (
                    "email_digest_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("push_task_assigned", models.BooleanField(default=True)),
                ("push_task_completed", models.BooleanField(default=True)),
                ("push_task_overdue", models.BooleanField(default=True)),
                ("push_task_due_soon", models.BooleanField(default=True)),
                ("push_comment_added", models.BooleanField(default=True)),
                ("push_mention", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
    ]
